apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: spring-mysql-app
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==  # 위에서 인코딩한 값
  MYSQL_USER: dXNlcjAx           # 'springuser' 인코딩
  MYSQL_PASSWORD: dXNlcjAx       # 'springpass' 인코딩
